"use client";

import { motion } from "framer-motion";
import { Mail, Sparkles, Clock, ArrowRight } from "lucide-react";

export default function SceneAutoFollowUp() {
  return (
    <section className="w-full bg-web-bg-0">
      <div className="max-w-[1300px] mx-auto px-6 md:px-20 py-20 md:py-32">
        {/* Step indicator */}
        <motion.div
          className="flex items-center gap-3 mb-8"
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#22C55E]/10">
            <span className="text-sm font-bold text-[#22C55E]">3</span>
          </div>
          <span className="text-[13px] font-medium tracking-wide text-text-2 uppercase">
            Auto Follow-up
          </span>
        </motion.div>

        <motion.div
          className="flex flex-col md:flex-row md:items-end gap-8 md:gap-12"
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        >
          {/* Left: Text */}
          <div className="flex w-full md:w-[380px] md:shrink-0 flex-col justify-end gap-4 pb-0 md:pb-6">
            <h2 className="text-[28px] md:text-[36px] font-bold leading-tight text-text-0">
              Follow-ups that write themselves
            </h2>
            <p className="text-[15px] leading-relaxed text-text-2">
              After every meeting, LUCI automatically drafts meeting notes and
              follow-up emails — including key decisions, action items, and next
              steps. One click to send.
            </p>
          </div>

          {/* Right: Follow-up Email Mockup */}
          <div
            className="flex flex-1 items-end justify-end overflow-hidden rounded-[20px] p-5 md:p-10"
            style={{
              backgroundImage: "url(/pb.webp)",
              backgroundSize: "cover",
              backgroundPosition: "center",
            }}
          >
            <div
              className="w-full overflow-hidden rounded-xl bg-white"
              style={{ boxShadow: "0 8px 32px rgba(0,0,0,0.18)" }}
            >
              {/* Header */}
              <div className="flex items-center justify-between border-b border-[#E5E7EB] px-6 py-4">
                <div className="flex items-center gap-2">
                  <Mail className="h-3.5 w-3.5 text-[#3B82F6]" />
                  <span className="text-[13px] font-semibold text-[#1A1A2E]">
                    Follow-up Draft
                  </span>
                </div>
                <span className="inline-flex items-center gap-1 rounded-full bg-[#8B5CF6]/10 px-2.5 py-0.5 text-[10px] font-semibold text-[#8B5CF6]">
                  <Sparkles className="h-3 w-3" />
                  Generated by LUCI
                </span>
              </div>

              {/* Email content */}
              <div className="px-6 py-5">
                {/* Meta */}
                <motion.div
                  className="flex flex-col gap-2 mb-5"
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: 0.2 }}
                >
                  <div className="flex items-center gap-2 text-[12px]">
                    <span className="text-[#9CA3AF] w-8">To:</span>
                    <span className="text-[#374151]">
                      james@team.com, lisa@team.com, david@team.com
                    </span>
                  </div>
                  <div className="flex items-center gap-2 text-[12px]">
                    <span className="text-[#9CA3AF] w-8">Re:</span>
                    <span className="font-medium text-[#1A1A2E]">
                      Weekly Standup Meeting Notes — Mar 24
                    </span>
                  </div>
                </motion.div>

                {/* Body */}
                <motion.div
                  className="flex flex-col gap-4 text-[12px] leading-relaxed text-[#374151]"
                  initial={{ opacity: 0, y: 8 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.35 }}
                >
                  <p>Hi team,</p>
                  <p>Here are the notes from today&apos;s standup:</p>

                  {/* Key decisions */}
                  <div className="rounded-lg border border-[#E5E7EB] bg-[#F9FAFB] px-4 py-3">
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-[#9CA3AF]">
                      Key Decisions
                    </span>
                    <ul className="mt-2 flex flex-col gap-1.5">
                      <li className="flex items-start gap-2">
                        <span className="text-[#E8622C] mt-0.5">•</span>
                        V2 prototype deadline set to March 28
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-[#E8622C] mt-0.5">•</span>
                        Client demo scheduled for March 30
                      </li>
                    </ul>
                  </div>

                  {/* Action items */}
                  <div className="rounded-lg border border-[#E5E7EB] bg-[#F9FAFB] px-4 py-3">
                    <span className="text-[10px] font-semibold uppercase tracking-wider text-[#9CA3AF]">
                      Action Items
                    </span>
                    <ul className="mt-2 flex flex-col gap-1.5">
                      <li className="flex items-center gap-2">
                        <ArrowRight className="h-3 w-3 text-[#3B82F6] shrink-0" />
                        <span>
                          <strong>James</strong> — Complete frontend prototype (Mar 28)
                        </span>
                      </li>
                      <li className="flex items-center gap-2">
                        <ArrowRight className="h-3 w-3 text-[#3B82F6] shrink-0" />
                        <span>
                          <strong>Lisa</strong> — Prepare test cases (Mar 26)
                        </span>
                      </li>
                      <li className="flex items-center gap-2">
                        <ArrowRight className="h-3 w-3 text-[#3B82F6] shrink-0" />
                        <span>
                          <strong>Sarah</strong> — Schedule client demo (Mar 30)
                        </span>
                      </li>
                    </ul>
                  </div>
                </motion.div>
              </div>

              {/* Footer */}
              <motion.div
                className="flex items-center justify-between border-t border-[#E5E7EB] px-6 py-3 bg-[#F9FAFB]"
                initial={{ opacity: 0 }}
                whileInView={{ opacity: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: 0.6 }}
              >
                <div className="flex items-center gap-1.5 text-[11px] text-[#9CA3AF]">
                  <Clock className="h-3 w-3" />
                  Generated 30s after meeting ended
                </div>
                <div className="flex items-center gap-2">
                  <span className="rounded-md border border-[#E5E7EB] px-3 py-1 text-[11px] font-medium text-[#6B7280] cursor-pointer hover:bg-[#F3F4F6]">
                    Edit
                  </span>
                  <span className="rounded-md bg-[#3B82F6] px-3 py-1 text-[11px] font-medium text-white cursor-pointer hover:bg-[#2563EB]">
                    Send
                  </span>
                </div>
              </motion.div>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
